language: node_js
node_js:
  — 7
script:
  — echo “Deploy!!”
install:
  — npm install -g firebase-tools
after_success:
  — firebase deploy — project landingpage-a96fd — token $FIREBASE_TOKEN.
branches:
  only:
    - release